version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medods
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
