port: "8080"
timeouts:
  write: 10
  read: 5
  idle: 15
jwt_secret: "medods_jwt"
database:
  user: "user"
  password: "password"
  host: "localhost"
  port: "5432"
  dbname: "medods"
mail:
  smtp_host: "stmp.somehost.com"
  smtp_port: 587
  smtp_username: "somefakeemail"
  smtp_password: "fakepassword"