port: ":8080"
timeouts:
  write: 10
  read: 5
  idle: 15
jwt_secret: "medods_jwt"
database:
  user: "user"
  password: "password"
  host: "postgres"
  port: "5432"
  dbname: "medods"
kafka:
  providers: kafka:9092